# Shell variables
# Generated by 'wal'
wallpaper='/home/jesusc/Pictures/Wallpapers/2mn8bo9krcx71.png'

# Special
background='#131219'
foreground='#c2dce4'
cursor='#c2dce4'

# Colors
color0='#131219'
color1='#8B78AF'
color2='#6F93CC'
color3='#73B1C3'
color4='#7DB8CF'
color5='#8E93BA'
color6='#84A7C7'
color7='#c2dce4'
color8='#879a9f'
color9='#8B78AF'
color10='#6F93CC'
color11='#73B1C3'
color12='#7DB8CF'
color13='#8E93BA'
color14='#84A7C7'
color15='#c2dce4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
