--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jesusc/Pictures/Wallpapers/2mn8bo9krcx71.png"

-- Special
background="#131219"
foreground="#c2dce4"
cursor="#c2dce4"

-- Colors
color0="#131219"
color1="#8B78AF"
color2="#6F93CC"
color3="#73B1C3"
color4="#7DB8CF"
color5="#8E93BA"
color6="#84A7C7"
color7="#c2dce4"
color8="#879a9f"
color9="#8B78AF"
color10="#6F93CC"
color11="#73B1C3"
color12="#7DB8CF"
color13="#8E93BA"
color14="#84A7C7"
color15="#c2dce4"
